
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Cartório</h3>
            </div>

        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Resultado da Consulta</h2>

                        <div class="clearfix"></div>

                        <div class="x_content">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nome</th>
                                    <th>Nº do Processo</th>
                                    <th>Estado</th>
                                    <th>Data de Criação</th>
                                    <th>Acção</th>
                                </tr>
                                </thead>


                                <tbody>
                                <?php for($i=0;$i<13;$i++):?>
                                <tr>
                                    <td><?php echo $i+1;?></td>
                                    <td>Emanuel Abel</td>
                                    <td><?php echo '0002'.$i;?></td>
                                    <td>Em andamento</td>
                                    <td>2011/04/25</td>
                                    <td><a href="#">Saber mais <i class="fa fa-eye right"></i></a></td>
                                </tr>
                                <?php endfor;?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->