<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>SICDoc | Error</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- Bootstrap -->
    <link href="<?php echo URL?>public/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo URL?>public/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo URL?>public/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo URL?>public/build/css/custom.min.css" rel="stylesheet">

</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center text-center">
                    <h1 class="error-number">Erro 404</h1>
                    <h2>Desculpa-nos, mas não podemos encontrar esta página</h2>
                    <label>
                        A página que estás procurando não existe ou foi removida.<br/>
                        Reporta este erro ao Administrador do Sistema.
                    </label>
                    <div class="mid_center">
                        <h3 style="color: #fff;">Contacto do Administrador do Sistema</h3>
                        <div class="col-xs-12 form-group pull-right top_search bg-white">
                            <h4>
                                <label class="">
                                    fontes204@gmail.com<br/>
                                    919 180 604
                                </label>
                            </h4>
                            <a href="javascript:window.history.go(-1)" title="Voltar" class="btn btn-sm btn-danger btn-block" style="text-align: left">
                                <i class="fa fa-long-arrow-left"></i> Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->
    </div>
</div>
</body>
</html>
