
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Criação de novo processo</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        &nbsp;&nbsp;
                        <span class="input-group-btn">
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix">

        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Preencha os campos abaixo</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <!-- Smart Wizard -->
                        <div id="wizard" class="form_wizard wizard_horizontal">
                            <ul class="wizard_steps">
                                <li>
                                    <a href="#step-1">
                                        <span class="step_no">1</span>
                                        <span class="step_descr">
                                            Dados do cliente
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-2">
                                        <span class="step_no">2</span>
                                        <span class="step_descr">
                                            Dados do imóvel
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-3">
                                        <span class="step_no">3</span>
                                        <span class="step_descr">
                                            Localização do imóvel
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-4">
                                        <span class="step_no">4</span>
                                        <span class="step_descr">
                                            Dados do vendedor
                                        </span>
                                    </a>
                                </li>
                            </ul>
                            <form class="form-horizontal form-label-left form-criar-processo" action="<?php echo URL?>processo/criar_processo">
                            <div id="step-1">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="nome" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div id="gender" class="btn-group" data-toggle="buttons">
                                                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                        <input type="radio" name="genero" value="m"> &nbsp; Masculino &nbsp;
                                                    </label>
                                                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                        <input type="radio" name="genero" value="f"> Femenino
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nº B.I </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="last-name" name="n-bi" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="n-nif" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>
                            <div id="step-2">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome do Condomínio </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="nome-condominio" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Tipo de Imóvel </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select id="id-tipo-imovel" class="select2_single form-control" name="tipo-imovel" tabindex="-1">
                                                    <option> --- Selecione --- </option>
                                                    <option value="Habitação">Habitação</option>
                                                    <option value="Loja">Loja</option>
                                                    <option value="Terreno">Terreno</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº Descrição do Prédio </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="n-descricao-predio" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Valor do Imóvel </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="valor-imovel" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>
                            <div id="step-3">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nº Condomínio </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="n-condominio" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Quadra </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="last-name" name="quadra" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Lote </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="lote" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Metragem do Lote </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="metragem-lote" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de Lote </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select id="id-tipo-lote" class="select2_single form-control" name="tipo-lote" tabindex="-1">
                                                    <option> --- Selecione --- </option>
                                                    <option value="Lote1">Lote 1</option>
                                                    <option value="Lote2">Lote 2</option>
                                                    <option value="Lote3">Lote 3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de Habitação </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select id="id-tipo-habitacao" class="select2_single form-control" name="tipo-habitacao" tabindex="-1">
                                                    <option> --- Selecione --- </option>
                                                    <option value="habitacao1">Tipo Habitação 1</option>
                                                    <option value="habitacao2">Tipo Habitação 2</option>
                                                    <option value="habitacao3">Tipo Habitação 3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Metragem da Habitação </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="metragem-habitacao" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Valor </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="valor" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>
                            <div id="step-4">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Empresa </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <label>
                                                    <input type="checkbox" name="tipo-vendedor" class="js-switch" />
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="nome-empresa" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div id="campo-empresa" class="hidden">
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Empresa </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="n-nif-empresa" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº B.I Responsável</label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="n-bi-responsavel" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Certidão Comercial </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="certidao-comercial" accept="image/*">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Empresa </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="nif-empresa" accept="image/*">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">B.I Responsável </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="bi-responsavel" accept="image/*">
                                                </div>
                                            </div>
                                        </div>
                                        <div id="campo-pessoa" class="">
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Vendedor</label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="n-nif-vendedor" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº B.I Vendedor</label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="n-bi-vendedor" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Vendedor</label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="nif-vendedor" accept="image/*">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">B.I Vendedor</label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="bi-vendedor" accept="image/*">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Comprador</label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="nif-comprador" accept="image/*">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">B.I Comprador</label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="bi-comprador" accept="image/*">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Contrato </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="contrato" accept="image/*">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Termo de Quitação </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="termo-quitacao" accept="image/*">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Certidão Predial </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="certidao-predial" accept="image/*">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>
                            </form>
                        </div>
                        <!-- End SmartWizard Content -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>