<?php
    $idFun = base64_decode($att->getParam());
    $fun = new FuncionarioDao();
    $funcionario = $fun->listarPorId('funcionario',$idFun);

    $nomeFunc = $funcionario->_nome . ' ' . $funcionario->_apelido;
    if($funcionario->_genero=='m') {
        $genero = 'Masculino';
    } else {
        $genero = 'Femenino';
    }
?>

<!-- page content -->
<div class="right_col" role="main" style="margin-bottom: -10px;">
    <div id="content" class="content">
        <!-- begin row -->
        <div class="row">
            <div class="animated flipInY col-lg-12 col-md-12 col-sm-6 col-xs-12">
                <div class="tile-stats bg-blue">
                    <div class="icon" style="color: #fff;"><i class="fa fa-info-circle "></i></div>
                    <div class="count">
                        <i class="fa fa-user"></i> <?php echo $nomeFunc;?>
                    </div>
                    <h3 style="color: #fff;"><i class="fa fa-file-text" ></i>
                        <?php if($funcionario->_id_area == '1')
                            echo 'Back-Office';
                        elseif ($funcionario->_id_area == '2')
                            echo 'Gerência';?>
                    </h3>
                </div>
            </div>
        </div>
        <!-- end row -->
        <!-- begin row -->
        <div class="row">
            <!-- begin col-10 -->
            <div class="col-md-9">
                <!-- begin panel -->
                <div class="x_panel">
                    <div class="row">
                        <!-- begin profile-left -->
                        <div class="col-xs-3">
                            <!-- begin profile-image -->
                            <div class="profile-image" style="width: 100%; height: 25%;">
                                <img class="img-thumbnail txt-ij" style="width: inherit;height: inherit"
                                     src="<?php echo URL ?>public/images/perfil/<?php echo $funcionario->_foto;?>"/>
                            </div>
                            <!-- end profile-image -->
                            <div class="hidden-sm hidden-xs" style="width: 100%;SS">
                                <p>
                                    <a href="<?php echo URL.$att->getContoller()?>/alterarCredenciais/<?php echo base64_encode($idFun);?>"
                                       class="btn btn-sm btn-primary btn-block" style="text-align: left">
                                        <i class="fa fa-edit"></i> Alterar Credênciais</a>
                                    <a href="javascript:window.history.go(-1)" title="Voltar" class="btn btn-sm btn-default btn-block" style="text-align: left">
                                        <i class="fa fa-long-arrow-left"></i> Voltar</a>
                                </p>
                            </div>
                        </div>
                        <!-- end profile-left -->
                        <!-- begin profile-right -->
                        <div class="col-xs-8 col-lg-push-1">
                            <!-- begin table -->
                            <div class="table-responsivse" style="border-left: 1px">
                                <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados Pessoais</h6>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Gênero</th>
                                        <th>Data de Nascimento</th>
                                        <th>N&ordm; do Bilhete</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td class="text-capitalize"><?php echo $nomeFunc?></td>
                                        <td class="text-capitalize"><?php echo $genero?></td>
                                        <td class="text-capitalize"><?php echo $att->DataAo($funcionario->_data_nascimento)?></td>
                                        <td class="text-capitalize"><?php echo $funcionario->_num_bi?></td>
                                    </tr>
                                    <hr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="" style="margin-top: -7%">
                                    <h6 class="text-primary"> <i class="fa fa-phone"></i> Contactos <span class="f-s-9 text-inverse">
                                            &</span> <i class="fa fa-home"></i> Morada
                                    </h6>
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Telefone</th>
                                            <th>E-mail</th>
                                            <th>Morada</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td class="text-capitalize"><?php echo $funcionario->_telefone;?></td>
                                            <td class="text-lowercase"><?php echo $funcionario->_email;?></td>
                                            <td class="text-capitalize"><?php echo $funcionario->_morada;?></td>
                                        </tr>
                                        <hr>
                                        <tr>
                                            <td>&nbsp;</td>
                                            <td>&nbsp;</td>
                                            <td>&nbsp;</td>
                                            <td>&nbsp;</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- end table -->
                        </div>
                        <!-- end profile-right -->
                    </div>
                </div>
                <!-- end panel -->
            </div>
            <!-- end col-10 -->
            <div class="col-md-3">
                <div class="panel panel-primary" data-sortable-id="index-9">
                    <div class="panel-heading">
                        <h4 class="panel-title">&nbsp;</h4>
                    </div>
                    <div class="panel-body p-0 image gallery-group-1">
                        <div class="panel-body p-0 image gallery-group-1">
                            <ul class="todolist">
                                <li>
                                    <div id="datepicker-inline" class="datepicker-full-width"><div></div></div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end #content -->
</div>
<!-- end page content -->
