
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Página Inicial</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <br />&nbsp
                        <span class="input-group-btn">

                    </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2 class="nav navbar-left panel_toolbox">
                            <a class="text-primary">SICDoc</a> - Sistema de Informação e Controlo de Documentos
                        </h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class=""></div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-4">
                                <img src="<?php echo URL?>public/img/doc.png" />
                            </div>
                            <div class="col-md-5"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->