
<!-- page content -->
<div class="right_col" role="main"  style="margin-bottom: -10px">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Criação de novo funcionário</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        &nbsp;&nbsp;
                        <span class="input-group-btn">
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix">

        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Preencha os campos abaixo</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <form class="form-horizontal form-label-left form-criar-funcionario" action="<?php echo URL?>funcionario/criar_funcionario">
                            <!-- begin row -->
                            <div class="row">
                                <!-- begin col-6 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="nome" required="required" name="nome" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Apelido </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="nome" required="required" name="apelido" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <div id="gender" class="btn-group" data-toggle="buttons">
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="genero" value="m"> &nbsp; Masculino &nbsp;
                                                </label>
                                                <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="genero" value="f"> Femenino
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nº B.I </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="last-name" name="n-bi" required="required" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Data de nascimento </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input id="middle-name" type="date" name="data-nascimento" required="required" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                </div>
                                <!-- end col-6 -->

                                <!-- begin col-6 -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Morada </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input id="middle-name" type="text" name="morada" required="required" placeholder="Municipio, Bairro, Rua" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Telefone </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="nome" required="required" name="telefone" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">E-mail </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="email" id="nome" required="required" name="email" class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Função </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <select class="select2_single form-control text-center" name="funcao" tabindex="-1">
                                                <option value="-1"> --- Selecione --- </option>
                                                <option value="1">Back-Office </option>
                                                <option value="2">Gerência </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Fotografia </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="file" class="col-md-7 col-xs-12" id="inputImage" name="foto" accept="image/*">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- end row -->
                            <div class="row">
                                <div class="col-md-5"></div>
                                <div class="col-md-2">
                                    <div class="form-group ">
                                        <input type="submit" class="btn btn-primary btn-block" id="btn-funcionario" value="Guardar" />
                                    </div>
                                </div>
                                <div class="col-md-5"></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade calback-criar-funcionario" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title left"><span class="text-info">SIC</span>Doc informa</h6>
            </div>
            <div class="modal-body corpo-modal">

            </div>
            <div class="modal-footer">
                <a href="javascript:;" id="id_fechar_modal" class="btn btn-sm btn-inverse" data-dismiss="modal">Fechar</a>
            </div>
        </div>
    </div>
</div>