
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Criação de novo funcionário</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        &nbsp;&nbsp;
                        <span class="input-group-btn">
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix">

        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Preencha os campos abaixo</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <!-- Smart Wizard -->
                        <div id="wizard" class="form_wizard wizard_horizontal">
                            <ul class="wizard_steps">
                                <li>
                                    <a href="#step-1">
                                        <span class="step_no">1</span>
                                        <span class="step_descr">
                                            Dados Pessoais
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-2">
                                        <span class="step_no">2</span>
                                        <span class="step_descr">
                                            Contactos e Morada
                                        </span>
                                    </a>
                                </li>
                            </ul>
                            <form class="form-horizontal form-label-left form-criar-funcionario" action="<?php echo URL?>funcionario/criar_funcionario">
                            <div id="step-1">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="nome" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div id="gender" class="btn-group" data-toggle="buttons">
                                                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                        <input type="radio" name="genero" value="m"> &nbsp; Masculino &nbsp;
                                                    </label>
                                                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                        <input type="radio" name="genero" value="f"> Femenino
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nº B.I </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="last-name" name="n-bi" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Data de nascimento </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="date" name="data-nascimento" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>
                            <div id="step-2">
                                <!-- begin row -->
                                <div class="row">
                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Telefone </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="nome" required="required" name="telefone" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">E-mail </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="email" id="nome" required="required" name="email" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Função </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <select id="id-tipo-imovel" class="select2_single form-control" name="funcao" tabindex="-1">
                                                    <option value="0"> --- Selecione --- </option>
                                                    <option value="Recepção">Recepção </option>
                                                    <option value="Secretariado">Secretariado </option>
                                                    <option value="Gerência">Gerência </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end col-6

                                    <!-- begin col-6 -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Morada </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="text" name="morada" required="required" placeholder="Municipio, Bairro, Rua" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Fotografia </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input id="middle-name" type="file" name="foto" class="col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                            </div>

                            </form>
                        </div>
                        <!-- End SmartWizard Content -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>