<?php
$att = new Atributo();
$imovel = new Imovel();
$imovelDao = new ImovelDao();
$rtnImovel = $imovelDao->listarTodosImoveis();

$clienteDao = new ClienteDao();

?>
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Todos os Processos</h3>
            </div>

        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Os processos estão organizados por data de criação</h2>
                        <div class="clearfix"></div>

                        <div class="x_content">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nome Comprador</th>
                                    <th>Nº do Processo</th>
                                    <th>Estado</th>
                                    <th>Tipo de Imóvel</th>
                                    <th>Data de Criação</th>
                                    <th>Acção</th>
                                </tr>
                                </thead>


                                <tbody>
                                <?php for($i=0;$i<count($rtnImovel);$i++):
                                    $nome = $clienteDao->listarPorId('cliente',$rtnImovel[$i]->_id_cliente);
                                    $n_processo = $rtnImovel[$i]->_n_processo;
                                    $tipoImovel = $rtnImovel[$i]->_tipo_imovel;
                                    $data = $rtnImovel[$i]->_data_criacao;
                                    $id = base64_encode($rtnImovel[$i]->_id_cliente);
                                    ?>
                                    <tr>
                                        <td><?php echo $i+1;?></td>
                                        <td><?php echo $nome->_nome;?></td>
                                        <td><?php echo $n_processo;?></td>
                                        <td>
                                            <?php
                                            if($rtnImovel[$i]->_id_estado == '1') {
                                                echo 'Pendente de Pagamento';
                                            } elseif ($rtnImovel[$i]->_id_estado == '2') {
                                                echo 'Pendente das Finanças';
                                            } elseif ($rtnImovel[$i]->_id_estado == '3'){
                                                echo 'Pendente de Escritur';
                                            } elseif ($rtnImovel[$i]->_id_estado == '4'){
                                                echo 'Pendente de Registo';
                                            } elseif ($rtnImovel[$i]->_id_estado == '5'){
                                                echo 'Concluídos';
                                            }
                                            ?>
                                        </td>
                                        <td><?php echo $tipoImovel;?></td>
                                        <td><?php echo $data;?></td>
                                        <td><a href="<?php echo URL.$att->getContoller().'/visualizar/'.$id;?>">Ver <i class="fa fa-eye right"></i></a></td>
                                    </tr>
                                <?php endfor;?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->