
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Criação de novo processo</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        &nbsp;&nbsp;
                        <span class="input-group-btn">
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix">

        </div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Preencha os campos abaixo</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <!-- Smart Wizard -->
                        <div id="wizard" class="form_wizard wizard_horizontal">
                            <ul class="wizard_steps">
                                <li>
                                    <a href="#step-1">
                                        <span class="step_no">1</span>
                                        <span class="step_descr">
                                            Dados do cliente
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-2">
                                        <span class="step_no">2</span>
                                        <span class="step_descr">
                                            Dados do imóvel
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-3">
                                        <span class="step_no">3</span>
                                        <span class="step_descr">
                                            Localização do imóvel
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#step-4">
                                        <span class="step_no">4</span>
                                        <span class="step_descr">
                                            Dados do vendedor
                                        </span>
                                    </a>
                                </li>
                            </ul>
                            <form class="form-horizontal form-label-left form-criar-processo" action="<?php echo URL?>processo/criar_processo" enctype="multipart/form-data">
                                <div id="step-1">
                                    <!-- begin row -->
                                    <div class="row">
                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="nome" required="required" name="nome" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <div id="gender" class="btn-group" data-toggle="buttons">
                                                        <label class="btn btn-default gender-genero" val="m" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                            <input type="radio" name="genero" value="m"> &nbsp;&nbsp; Masculino &nbsp;&nbsp;&nbsp;
                                                        </label>
                                                        <label class="btn btn-primary gender-genero" val="f" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                            <input type="radio" name="genero" value="f"> &nbsp;&nbsp; Femenino &nbsp;&nbsp;&nbsp;
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Estado Civil </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <select id="id-estado-civil" class="select2_single form-control text-center" name="estado-civil" tabindex="-1">
                                                        <option value="Solteiro">Solteiro</option>
                                                        <option value="Casado">Casado</option>
                                                        <option value="Divorciado">Divorciado</option>
                                                        <option value="Viúvo">Viúvo</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end col-6

                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Nº B.I </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="last-name" name="n-bi" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="" type="text" name="n-nif" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div id="casamento">
                                                <div class="form-group">
                                                    <label id="lbl-n-bi" class="control-label col-md-3 col-sm-3 col-xs-12" >Número do B.I da Esposa </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" id="" name="n-bi-esposa" class="form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end row -->
                                </div>
                                <div id="step-2">
                                    <!-- begin row -->
                                    <div class="row">
                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome do Condomínio </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="nome" required="required" name="nome-condominio" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Tipo de Imóvel </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <select id="id-tipo-imovel" class="select2_single form-control text-center" name="tipo-imovel" tabindex="-1">
                                                        <option value="Nenhum"> --- Selecione --- </option>
                                                        <option value="Habitação">Habitação</option>
                                                        <option value="Loja">Loja</option>
                                                        <option value="Terreno">Terreno</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end col-6

                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº Descrição do Prédio </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="n-descricao-predio" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Valor do Imóvel </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="valor-imovel" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end row -->
                                </div>
                                <div id="step-3">
                                    <!-- begin row -->
                                    <div class="row">
                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nº Condomínio </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="nome" required="required" name="n-condominio" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Quadra </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="last-name" name="quadra" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Lote </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="lote" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Metragem do Lote </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="metragem-lote" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end col-6

                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de Lote </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <select id="id-tipo-lote" class="select2_single form-control" name="tipo-lote" tabindex="-1">
                                                        <option value="Nenhum"> --- Selecione --- </option>
                                                        <option value="Lote1">Lote 1</option>
                                                        <option value="Lote2">Lote 2</option>
                                                        <option value="Lote3">Lote 3</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Tipo de Habitação </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <select id="id-tipo-habitacao" class="select2_single form-control" name="tipo-habitacao" tabindex="-1">
                                                        <option value="Nenhum"> --- Selecione --- </option>
                                                        <option value="T1">T1</option>
                                                        <option value="T2">T2</option>
                                                        <option value="T3">T3</option>
                                                        <option value="T4">T4</option>
                                                        <option value="T5">T5</option>
                                                        <option value="T4+1">T4+1</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Metragem da Habitação </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input id="middle-name" type="text" name="metragem-habitacao" required="required" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end row -->
                                </div>
                                <div id="step-4">
                                    <!-- begin row -->
                                    <div class="row">
                                        <!-- begin col-6 -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Empresa </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <label>
                                                        <input id="check-empresa" type="checkbox" name="tipo-vendedor" class="js-switch" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nome Vendedor </label>
                                                <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="nome" required="required" name="nome-vendedor" class="form-control col-md-7 col-xs-12">
                                                </div>
                                            </div>
                                            <div id="campo-empresa" class="">
                                                <div class="form-group">
                                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Empresa </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="middle-name" type="text" name="n-nif-empresa" required="required" class="input-empresa-txt form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº B.I Representante</label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="middle-name" type="text" name="n-bi-responsavel" required="required" class="input-empresa-txt form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nome Representante </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" class="input-empresa-txt form-control col-md-7 col-xs-12" id="inputImage" name="nome-responsavel" accept="image/*">
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="campo-pessoa" class="">
                                                <div class="form-group">
                                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">NIF Vendedor</label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="middle-name" type="text" name="n-nif-vendedor" required="required" class="input-pessoa-txt form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Nº B.I Vendedor</label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input id="middle-name" type="text" name="n-bi-vendedor" required="required" class="input-pessoa-txt form-control col-md-7 col-xs-12">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end col-6

                                        <!-- begin col-6 -->
                                        <div class="col-md-6">

                                        </div>
                                    </div>
                                    <!-- end row -->
                                </div>
                            </form>
                        </div>
                        <!-- End SmartWizard Content -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade callback-criar-processo" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title left"><span class="text-info">SIC</span>Doc informa</h6>
            </div>
            <div class="modal-body corpo-modal">

            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" onclick="window.print();"><i class="fa fa-print"></i> Imprimir </button>
                <a href="javascript:;" id="id_fechar_modal" class="btn btn-default" data-dismiss="modal">Fechar</a>
            </div>
        </div>
    </div>
</div>