<?php

$att = new Atributo();
$hlp = new Helper();
$idCliente = base64_decode($att->getParam());

$imovelDao = new ImovelDao();
$rtnImovel = $imovelDao->listarPelaChaveEstrangeira("imovel","_id_cliente",$idCliente);

$localizacaoDao = new LocalizacaoDao();
$rtnLocal = $localizacaoDao->listarPorId('localizacao',$rtnImovel->_id);

$d = explode(' ',$rtnImovel->_data_criacao);
$data = $d[0];

$clienteDao = new ClienteDao(); //var_dump($rtnImovel[$i]->_id_cliente)
$rtnCliente = $clienteDao->listarPorId('cliente',$idCliente);


$vendedorDao = new VendedorDao();
$rtnVendedor = $vendedorDao->listarPorId('vendedor',$rtnImovel->_id_vendedor);

$empresaDao = new EmpresaDao();
$pessoaDao = new Pessoa_FisicaDao();
$ctrl = 0;

$rtnEmpresa = $empresaDao->listarPelaChaveEstrangeira('empresa','_id_vendedor', $rtnVendedor->_id);
$rtnPessoa = $pessoaDao->listarPelaChaveEstrangeira('pessoa_fisica','_id_vendedor',$rtnVendedor->_id);

if(is_object($rtnEmpresa)) {
    $ctrl = 1;
}elseif(is_object($rtnPessoa)){
    $ctrl = 2;

}

?>
<!-- page content -->
<div class="right_col" role="main">
    <div id="content" class="content">
        <!-- begin row -->
        <div class="row">
            <div class="animated flipInY col-lg-12 col-md-12 col-sm-6 col-xs-12">
                <div class="tile-stats bg-blue">
                    <div class="icon" style="color: #fff;"><i class="fa fa-info-circle "></i></div>
                    <div class="count">
                        <i class="fa fa-user"></i> <?php echo $rtnCliente->_nome; ?>
                    </div>
                    <h3 style="color: #fff;"><i class="fa fa-file-text" ></i> N&ordm; Processo: <?php echo $rtnImovel->_n_processo; ?></h3>
                </div>
            </div>
        </div>
        <!-- end row -->
        <div class="row">
            <div class="col-md-9">
                <div class="x_panel">
                    <div class="x_title">
                        <div class="col-xs-3">
                            <ul class="nav nav-tabs tabs-left">
                                <li class="active"><a href="#home" data-toggle="tab">Comprador</a>
                                </li>
                                <li><a href="#profile" data-toggle="tab">Imóvel</a>
                                </li>
                                <li><a href="#messages" data-toggle="tab">Localização</a>
                                </li>
                                <li><a href="#settings" data-toggle="tab">Vendedor</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-xs-9">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="home">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados Pessoais</h6>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Nome</th>
                                                    <th>Gênero</th>
                                                    <th>B.I</th>
                                                    <th>NIF</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnCliente->_nome; ?></td>
                                                <td class="text-capitalize"><?php echo $rtnCliente->_genero; ?></td>
                                                <td><?php echo $rtnCliente->_bi; ?></td>
                                                <td><?php echo $rtnCliente->_nif; ?></td>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">
                                            <h6 class="text-primary"><i class="fa fa-upload"></i>
                                                Documentos do Comprador
                                            </h6>
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Carregar B.I</th>
                                                        <th>Carregar NIF</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="form-group">
                                                            <input name="bi" id="bi" type="file" class="form-control"/>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">
                                                            <input name="nif" id="nif" type="file" class="form-control"/>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="profile">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados do Imóvel</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Nome do Condominio</th>
                                                <th>Tipo Imóvel</th>
                                                <th>Valor do Imóvel</th>
                                                <th>Data de Entrada</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnImovel->_nome_condominio; ?></td>
                                                <td><?php echo $rtnImovel->_tipo_imovel; ?></td>
                                                <td><?php echo $rtnImovel->_valor; ?></td>
                                                <td><?php echo $data; ?></td>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="messages">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Localização do Imóvel</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Nº do Condominio</th>
                                                <th>Tipo de Habitação</th>
                                                <th>Metragem da Habitação</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnLocal->_n_condominio; ?></td>
                                                <td><?php echo $rtnLocal->_tipo_habitacao; ?></td>
                                                <td><?php echo $rtnLocal->_metragem_habitacao; ?></td>
                                            </tr>

                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">

                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>Quadra</th>
                                                    <th>Lote</th>
                                                    <th>Tipo de Lote</th>
                                                    <th>Metragem do Lote</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td><?php echo $rtnLocal->_quadra; ?></td>
                                                    <td><?php echo $rtnLocal->_lote; ?></td>
                                                    <td><?php echo $rtnLocal->_tipo_lote; ?></td>
                                                    <td><?php echo $rtnLocal->_metragem_lote; ?></td>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="settings">

                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados do Vendedor</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <?php if($ctrl==1):?>
                                                    <th>Nome da Empresa</th>
                                                <?php elseif($ctrl==2):?>
                                                    <th>Nome do Vendedor</th>
                                                <?php endif;?>
                                                <th>NIF Vendedor</th>
                                                <?php if($ctrl==1):?>
                                                    <th>B.I do Representante</th>
                                                <?php elseif($ctrl==2):?>
                                                    <th>B.I do Vendedor</th>
                                                <?php endif;?>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnVendedor->_nome; ?></td>
                                                <td><?php echo $rtnVendedor->_n_nif; ?></td>
                                                <?php if($ctrl==1):?>
                                                    <td><?php echo $rtnEmpresa->_n_bi_representate; ?></td>
                                                <?php elseif($ctrl==2):?>
                                                    <td><?php echo $rtnPessoa->_n_bi; ?></td>
                                                <?php endif;?>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">
                                            <?php if($ctrl==1):?>
                                                <h6 class="text-primary"><i class="fa fa-list-alt"></i> Documentos da Empresa e do Representante</h6>
                                            <?php elseif($ctrl==2):?>
                                                <h6 class="text-primary"><i class="fa fa-list-alt"></i> Documentos do Vendedor</h6>
                                            <?php endif;?>
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <?php if($ctrl==1):?>
                                                        <th>Carregar B.I Representante</th>
                                                    <?php elseif($ctrl==2):?>
                                                        <th>Carregar B.I</th>
                                                    <?php endif;?>
                                                    <th>Carregar NIF</th>
                                                    <th>Carregar Contrato</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <?php if($ctrl==1):?>
                                                        <td>
                                                            <div class="form-group"><input name="bi-representante" id="bi-representante" type="file" class="form-control"/></div>
                                                        </td>
                                                    <?php elseif($ctrl==2):?>
                                                        <td>
                                                            <div class="form-group"><input name="bi-pessoa" id="bi-pessoa" type="file" class="form-control"/></div>
                                                        </td>
                                                    <?php endif;?>
                                                    <td>
                                                        <div class="form-group"><input name="nif-pessoa" id="nif-pessoa" type="file" class="form-control"/></div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group"><input name="contrato" id="contrato" type="file" class="form-control"/></div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th>Carregar Termo de Quitação</th>
                                                    <th>Carregar Certidão Predial</th>
                                                    <?php if($ctrl==1):?>
                                                        <th>Certidão Comercial</th>
                                                    <?php elseif($ctrl==2):?>
                                                        <th>&nbsp;</th>
                                                    <?php endif;?>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="form-group"><input name="termo-quitacao" id="termo-quitacao" type="file" class="form-control"/></div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group"><input name="certidao-predial" id="certidao-predial" type="file" class="form-control"/></div>
                                                    </td>
                                                    <?php if($ctrl==1):?>
                                                        <td>
                                                            <div class="form-group"><input name="certidao-comercial" id="certidao-comercial" type="file" class="form-control"/></div>
                                                        </td>
                                                    <?php elseif($ctrl==2):?>
                                                        <td>&nbsp;</td>
                                                    <?php endif;?>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer" style="border: none; background-color: #fff;">
                        <a href="javascript:window.history.go(-1)" title="Voltar" class="btn btn-sm btn-default">Voltar</a>
                        <div class="pull-right f-s-14">
                            <i class="fa fa-clock-o"></i> Tempo de existência: <span
                                    class="text-primary"><?php echo substr($hlp->tempoEspera($data, date('Y-m-d')), 1) ?></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="panel panel-primary" data-sortable-id="index-9">
                    <div class="panel-heading">
                        <h4 class="panel-title">Documentos do Processo</h4>
                    </div>
                    <div class="panel-body p-0 image gallery-group-1">
                        <ul class="todolist">
                            <li>
                                <a href="#" class="todolist-container" data-toggle="modal" data-target=".modal-imagem">
                                    <div class="todolist-input"><i class="fa fa-list-alt text-primary"></i></div>
                                    <div class="todolist-title"><?php echo 'Alguma coisa'; ?></div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="todolist-container" data-lightbox="gallery-group-1">
                                    <div class="todolist-input"><i class="fa fa-map-o text-primary"></i></div>
                                    <div class="todolist-title"><?php echo 'Alguma coisa'; ?></div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="todolist-container" data-lightbox="gallery-group-1">
                                    <div class="todolist-input"><i class="fa fa-list-alt text-primary"></i></div>
                                    <div class="todolist-title"><?php echo 'Alguma coisa'; ?></div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="todolist-container" data-lightbox="gallery-group-1">
                                    <div class="todolist-input"><i class="fa fa-picture-o text-primary"></i></div>
                                    <div class="todolist-title"><?php echo 'Alguma coisa'; ?></div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->


<div class="modal fade modal-imagem" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div class="profile-image">
                    <img src="<?php echo URL?>public/images/media.jpg"/>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
            </div>

        </div>
    </div>
</div>
