<?php

$att = new Atributo();
$hlp = new Helper();
$idCliente = base64_decode($att->getParam());

$imovelDao = new ImovelDao();
$rtnImovel = $imovelDao->listarPelaChaveEstrangeira("imovel","_id_cliente",$idCliente);

$localizacaoDao = new LocalizacaoDao();
$rtnLocal = $localizacaoDao->listarPelaChaveEstrangeira('localizacao','_id_imovel',$rtnImovel->_id);

$d = explode(' ',$rtnImovel->_data_criacao);
$data = $d[0];

$clienteDao = new ClienteDao(); //var_dump($rtnImovel[$i]->_id_cliente)
$rtnCliente = $clienteDao->listarPorId('cliente',$idCliente);

$vendedorDao = new VendedorDao();
$rtnVendedor = $vendedorDao->listarPorId('vendedor',$rtnImovel->_id_vendedor);

$empresaDao = new EmpresaDao();
$pessoaDao = new Pessoa_FisicaDao();
$ctrl = 0;

$rtnEmpresa = $empresaDao->listarPelaChaveEstrangeira('empresa','_id_vendedor', $rtnVendedor->_id);
$rtnPessoa = $pessoaDao->listarPelaChaveEstrangeira('pessoa_fisica','_id_vendedor',$rtnVendedor->_id);

if(is_object($rtnEmpresa)) {
    $ctrl = 1;
}elseif(is_object($rtnPessoa)){
    $ctrl = 2;
}

$doc_pessoal = new Doc_Pessoal();
$doc_pessoalDao = new Doc_PessoalDao();
//$rtnDoc_pessoal = $doc_pessoalDao->listarPelaChaveEstrangeiraALL("doc_pessoal","_id_cliente",$idCliente);

/*
if(isset($_GET['erro']))
    $erro = $_GET['erro'];*/
?>
<!-- page content -->
<div class="right_col" role="main">
    <div id="content" class="content">
        <!-- begin row -->
        <div class="row">
            <div class="animated flipInY col-lg-12 col-md-12 col-sm-6 col-xs-12">
                <div class="tile-stats bg-blue">
                    <div class="icon" style="color: #fff;"><i class="fa fa-info-circle "></i></div>
                    <div class="count">
                        <i class="fa fa-user"></i> <?php echo $rtnCliente->_nome; ?>
                        <?php if($rtnImovel->_id_estado == 5):?>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <label>Processo Concluído</label>
                        <?php endif;?>
                    </div>
                    <h3 style="color: #fff;"><i class="fa fa-file-text" ></i> N&ordm; Processo: <?php echo $rtnImovel->_n_processo; ?></h3>
                </div>
            </div>
        </div>
        <!-- end row -->
        <div class="row">
            <div class="col-md-9">
                <div class="x_panel">
                    <div class="x_title">
                        <div class="col-xs-3">
                            <ul class="nav nav-tabs tabs-left">
                                <li class="active"><a href="#home" data-toggle="tab"><h2>Comprador</h2></a></li>
                                <li><a href="#profile" data-toggle="tab"><h2>Imóvel</h2></a></li>
                                <li><a href="#messages" data-toggle="tab"><h2>Localização</h2></a></li>
                                <li><a href="#settings" data-toggle="tab"><h2>Vendedor</h2></a></li>
                                <li><a href="#anothers" data-toggle="tab"><h2>Outros Dados</h2></a></li>
                            </ul>
                        </div>

                        <div class="col-xs-9">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="home">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados Pessoais</h6>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Nome</th>
                                                    <th>Gênero</th>
                                                    <th>B.I</th>
                                                    <th>NIF</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnCliente->_nome; ?></td>
                                                <td class="text-capitalize"><?php echo $rtnCliente->_genero; ?></td>
                                                <td><?php echo $rtnCliente->_bi; ?></td>
                                                <td><?php echo $rtnCliente->_nif; ?></td>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">
                                            <h6 class="text-primary"><i class="fa fa-upload"></i>
                                                Documentos do Comprador
                                            </h6>
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>B.I</th>
                                                        <th>NIF</th>
                                                        <th>Estado Civil</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                                $bi_compr = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'bi-compr');

                                                            if ($bi_compr == false  || !is_object($bi_compr)){
                                                            ?>
                                                            <label class="target-dir btn btn-primary" tipo="bi-compr"
                                                                   data-toggle="modal" data-target=".modal-doc-pessoal">Carregar B.I</label>
                                                            <?php
                                                            }else {
                                                                $extencao_bi_compr = explode('.',$bi_compr->_nome);
                                                                $dados_bi_compr = URL . $bi_compr->_caminho . $bi_compr->_nome;
                                                                if($extencao_bi_compr[count($extencao_bi_compr)-1] == 'pdf'){
                                                            ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_bi_compr; ?>" target="_blank">
                                                                        Ver B.I
                                                                    </a>
                                                            <?php
                                                                }else {
                                                            ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_bi_compr; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver B.I
                                                                    </label>
                                                            <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                            $nif_compr = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'nif-compr');

                                                                if ($nif_compr == false  || !is_object($nif_compr)){
                                                            ?>
                                                            <label class="target-dir btn btn-primary" tipo="nif-compr"
                                                                   data-toggle="modal" data-target=".modal-doc-pessoal">Carregar NIF</label>
                                                            <?php
                                                                }else {
                                                                $extencao_nif_compr = explode('.',$nif_compr->_nome);
                                                                $dados_nif_compr = URL . $nif_compr->_caminho . $nif_compr->_nome;
                                                                if($extencao_nif_compr[count($extencao_nif_compr)-1] == 'pdf'){
                                                            ?>
                                                                <a class="btn btn-default"
                                                                   href="<?php echo $dados_nif_compr; ?>" target="_blank">
                                                                    Ver NIF
                                                                </a>
                                                            <?php
                                                                }else {
                                                            ?>
                                                            <label class="btn btn-default btn-ver"
                                                                   dados="<?php echo $dados_nif_compr; ?>"
                                                                   data-toggle="modal"
                                                                   data-target=".modal-imagem">
                                                                Ver NIF
                                                            </label>
                                                            <?php
                                                                    }
                                                                }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <?php echo $rtnCliente->_estado_civil;?>
                                                    </td>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="profile">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados do Imóvel</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Nome do Condominio</th>
                                                <th>Tipo Imóvel</th>
                                                <th>Valor do Imóvel</th>
                                                <th>Data de Entrada</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnImovel->_nome_condominio; ?></td>
                                                <td><?php echo $rtnImovel->_tipo_imovel; ?></td>
                                                <td><?php echo $rtnImovel->_valor; ?></td>
                                                <td><?php echo $data; ?></td>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="messages">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Localização do Imóvel</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Nº do Condominio</th>
                                                <th>Tipo de Habitação</th>
                                                <th>Metragem da Habitação</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnLocal->_n_condominio; ?></td>
                                                <td><?php echo $rtnLocal->_n_condominio; ?></td>
                                                <td><?php echo $rtnLocal->_tipo_habitacao; ?></td>
                                                <td><?php echo $rtnLocal->_metragem_habitacao; ?></td>
                                            </tr>

                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">

                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>Quadra</th>
                                                    <th>Lote</th>
                                                    <th>Tipo de Lote</th>
                                                    <th>Metragem do Lote</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td><?php echo $rtnLocal->_quadra; ?></td>
                                                    <td><?php echo $rtnLocal->_lote; ?></td>
                                                    <td><?php echo $rtnLocal->_tipo_lote; ?></td>
                                                    <td><?php echo $rtnLocal->_metragem_lote; ?></td>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="settings">

                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Dados do Vendedor</h6>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <?php if($ctrl==1):?>
                                                    <th>Nome da Empresa</th>
                                                <?php elseif($ctrl==2):?>
                                                    <th>Nome do Vendedor</th>
                                                <?php endif;?>
                                                <th>NIF Vendedor</th>
                                                <?php if($ctrl==1):?>
                                                    <th>B.I do Representante</th>
                                                <?php elseif($ctrl==2):?>
                                                    <th>B.I do Vendedor</th>
                                                <?php endif;?>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $rtnVendedor->_nome; ?></td>
                                                <td><?php echo $rtnVendedor->_n_nif; ?></td>
                                                <?php if($ctrl==1):?>
                                                    <td><?php echo $rtnEmpresa->_n_bi_representate; ?></td>
                                                <?php elseif($ctrl==2):?>
                                                    <td><?php echo $rtnPessoa->_n_bi; ?></td>
                                                <?php endif;?>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="" style="margin-top: -4%">
                                            <?php if($ctrl==1):?>
                                                <h6 class="text-primary"><i class="fa fa-list-alt"></i> Documentos da Empresa e do Representante</h6>
                                            <?php elseif($ctrl==2):?>
                                                <h6 class="text-primary"><i class="fa fa-list-alt"></i> Documentos do Vendedor</h6>
                                            <?php endif;?>
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <?php if($ctrl==1):?>
                                                        <th>B.I Representante</th>
                                                    <?php elseif($ctrl==2):?>
                                                        <th>B.I</th>
                                                    <?php endif;?>
                                                    <th>NIF</th>
                                                    <th>Contrato</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                            $bi_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'bi-vend');

                                                            if ($bi_vend == false  || !is_object($bi_vend)){
                                                                ?>
                                                                <label class="target-dir btn btn-primary" tipo="bi-vend"
                                                                       data-toggle="modal" data-target=".modal-doc-pessoal">Carregar B.I</label>
                                                                <?php
                                                            }else {
                                                                $extencao_bi_vend = explode('.',$bi_vend->_nome);
                                                                $dados_bi_vend = URL . $bi_vend->_caminho . $bi_vend->_nome;
                                                                if($extencao_bi_vend[count($extencao_bi_vend)-1] == 'pdf'){
                                                                    ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_bi_vend; ?>" target="_blank">
                                                                        Ver B.I
                                                                    </a>
                                                                    <?php
                                                                }else {
                                                                    ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_bi_vend; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver B.I
                                                                    </label>
                                                                    <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                            $nif_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'nif-vend');

                                                            if ($nif_vend == false  || !is_object($nif_vend)){
                                                                ?>
                                                                <label class="target-dir btn btn-primary" tipo="nif-vend"
                                                                       data-toggle="modal" data-target=".modal-doc-pessoal">Carregar NIF</label>
                                                                <?php
                                                            }else {
                                                                $extencao_nif_vend = explode('.',$nif_vend->_nome);
                                                                $dados_nif_vend = URL . $nif_vend->_caminho . $nif_vend->_nome;
                                                                if($extencao_nif_vend[count($extencao_nif_vend)-1] == 'pdf'){
                                                                    ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_nif_vend; ?>" target="_blank">
                                                                        Ver B.I
                                                                    </a>
                                                                    <?php
                                                                }else {
                                                                    ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_nif_vend; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver B.I
                                                                    </label>
                                                                    <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                            $contrato_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'contrato-vend');

                                                            if ($contrato_vend == false  || !is_object($contrato_vend)){
                                                                ?>
                                                                <label class="target-dir btn btn-primary" tipo="contrato-vend"
                                                                       data-toggle="modal" data-target=".modal-doc-pessoal">Carregar Contrato</label>
                                                                <?php
                                                            }else {
                                                                $extencao_contrato_vend = explode('.',$contrato_vend->_nome);
                                                                $dados_contrato_vend = URL . $contrato_vend->_caminho . $contrato_vend->_nome;
                                                                if($extencao_contrato_vend[count($extencao_contrato_vend)-1] == 'pdf'){
                                                                    ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_contrato_vend; ?>" target="_blank">
                                                                        Ver Contrato
                                                                    </a>
                                                                    <?php
                                                                }else {
                                                                    ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_contrato_vend; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver Contrato
                                                                    </label>
                                                                    <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th>Termo de Quitação</th>
                                                    <th>Certidão Predial</th>
                                                    <?php if($ctrl==1):?>
                                                        <th>Certidão Comercial</th>
                                                    <?php elseif($ctrl==2):?>
                                                        <th>&nbsp;</th>
                                                    <?php endif;?>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                             $termo_quitacao_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'termo-quitacao-vend');

                                                            if ($termo_quitacao_vend == false  || !is_object($termo_quitacao_vend)){
                                                                ?>
                                                                <label class="target-dir btn btn-primary" tipo="termo-quitacao-vend"
                                                                       data-toggle="modal" data-target=".modal-doc-pessoal">C. Termo de Quitação</label>
                                                                <?php
                                                            }else {
                                                                $extencao_termo_quitacao_vend = explode('.',$termo_quitacao_vend->_nome);
                                                                $dados_termo_quitacao_vend = URL . $termo_quitacao_vend->_caminho . $termo_quitacao_vend->_nome;
                                                                if($extencao_termo_quitacao_vend[count($extencao_termo_quitacao_vend)-1] == 'pdf'){
                                                                    ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_termo_quitacao_vend; ?>" target="_blank">
                                                                        Ver Termo de Quitação
                                                                    </a>
                                                                    <?php
                                                                }else {
                                                                    ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_termo_quitacao_vend; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver Termo de Quitação
                                                                    </label>
                                                                    <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="form-group">
                                                            <?php
                                                            $certi_predial_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'certidao-predial-vend');

                                                            if ($certi_predial_vend == false  || !is_object($certi_predial_vend)){
                                                                ?>
                                                                <label class="target-dir btn btn-primary" tipo="certidao-predial-vend"
                                                                       data-toggle="modal" data-target=".modal-doc-pessoal">C. Certidão Predial</label>
                                                                <?php
                                                            }else {
                                                                $extencao_certi_predial_vend = explode('.',$certi_predial_vend->_nome);
                                                                $dados_certi_predial_vend = URL . $certi_predial_vend->_caminho . $certi_predial_vend->_nome;
                                                                if($extencao_certi_predial_vend[count($extencao_certi_predial_vend)-1] == 'pdf'){
                                                                    ?>
                                                                    <a class="btn btn-default"
                                                                       href="<?php echo $dados_certi_predial_vend; ?>" target="_blank">
                                                                        Ver Certidão Predial
                                                                    </a>
                                                                    <?php
                                                                }else {
                                                                    ?>
                                                                    <label class="btn btn-default btn-ver"
                                                                           dados="<?php echo $dados_certi_predial_vend; ?>"
                                                                           data-toggle="modal"
                                                                           data-target=".modal-imagem">
                                                                        Ver Certidão Predial
                                                                    </label>
                                                                    <?php
                                                                }
                                                            }
                                                            ?>
                                                        </div>
                                                    </td>
                                                    <?php if($ctrl==1):?>
                                                        <td>
                                                            <div class="form-group">
                                                                <?php
                                                                $certi_comercial_vend = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'certi-comercial-vend');

                                                                if ($certi_comercial_vend == false  || !is_object($certi_comercial_vend)){
                                                                    ?>
                                                                    <label class="target-dir btn btn-primary" tipo="certi-comercial-vend"
                                                                           data-toggle="modal" data-target=".modal-doc-pessoal">C. Certidão Comercial</label>
                                                                    <?php
                                                                }else {
                                                                    $extencao_certi_comercial_vend = explode('.',$certi_comercial_vend->_nome);
                                                                    $dados_certi_comercial_vend = URL . $certi_comercial_vend->_caminho . $certi_comercial_vend->_nome;
                                                                    if($extencao_certi_comercial_vend[count($extencao_certi_comercial_vend)-1] == 'pdf'){
                                                                        ?>
                                                                        <a class="btn btn-default"
                                                                           href="<?php echo $dados_certi_comercial_vend; ?>" target="_blank">
                                                                            Ver Certidão Comercial
                                                                        </a>
                                                                        <?php
                                                                    }else {
                                                                        ?>
                                                                        <label class="btn btn-default btn-ver"
                                                                               dados="<?php echo $dados_certi_comercial_vend; ?>"
                                                                               data-toggle="modal"
                                                                               data-target=".modal-imagem">
                                                                            Ver Certidão Comercial
                                                                        </label>
                                                                        <?php
                                                                    }
                                                                }
                                                                ?>
                                                            </div>
                                                        </td>
                                                    <?php elseif($ctrl==2):?>
                                                        <td>&nbsp;</td>
                                                    <?php endif;?>
                                                </tr>
                                                <hr>
                                                <tr>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                    <td>&nbsp;</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <!-- end table -->
                                </div>
                                <div class="tab-pane" id="anothers">
                                    <!-- begin table -->
                                    <div class="table-responsivse" style="border-left: 1px">
                                        <h6 class="text-primary"><i class="fa fa-list-alt"></i> Outros Dados</h6>
                                        <?php
                                            $outrosDados = $clienteDao->listarPorId('cliente',$idCliente);

                                            if($outrosDados->_estado_civil == 'Casado' || $outrosDados->_estado_civil == 'Casada'){
                                                $parceiro = '';
                                                if($outrosDados->_genero == 'f') {
                                                    $parceiro = ' do Esposo';
                                                } else {
                                                    $parceiro = ' da Esposa';
                                                }
                                        ?>
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>
                                                    <?php echo 'Nº B.I '. $parceiro;?>
                                                </th>
                                                <th><?php echo 'B.I '.$parceiro;?></th>
                                                <th>Regime de Casamento</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><?php echo $outrosDados->_n_bi_esposa;?></td>
                                                <td>
                                                    <div class="form-group">
                                                        <?php
                                                        $outrosEsposa = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'bi-esposa');

                                                        if ($outrosEsposa == false  || !is_object($outrosEsposa)){
                                                            ?>
                                                            <label class="target-dir btn btn-primary" tipo="bi-esposa"
                                                                   data-toggle="modal" data-target=".modal-doc-pessoal">Carregar <?php echo 'B.I'.$parceiro;?></label>
                                                            <?php
                                                        }else {
                                                            $extencao_outrosEsposa = explode('.',$outrosEsposa->_nome);
                                                            $dados_outrosEsposa = URL . $outrosEsposa->_caminho . $outrosEsposa->_nome;
                                                            if($extencao_outrosEsposa[count($extencao_outrosEsposa)-1] == 'pdf'){
                                                                ?>
                                                                <a class="btn btn-default"
                                                                   href="<?php echo $dados_outrosEsposa; ?>" target="_blank">
                                                                    Ver <?php echo 'B.I'.$parceiro;?>
                                                                </a>
                                                                <?php
                                                            }else {
                                                                ?>
                                                                <label class="btn btn-default btn-ver"
                                                                       dados="<?php echo $dados_outrosEsposa; ?>"
                                                                       data-toggle="modal"
                                                                       data-target=".modal-imagem">
                                                                    Ver <?php echo 'B.I'.$parceiro;?>
                                                                </label>
                                                                <?php
                                                            }
                                                        }
                                                        ?>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <?php
                                                        $outro_Regime_casam = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_pessoal","_id_cliente",$idCliente,"_tipo",'regime-casamento');

                                                        if ($outro_Regime_casam == false  || !is_object($outro_Regime_casam)){
                                                            ?>
                                                            <label class="target-dir btn btn-primary" tipo="regime-casamento"
                                                                   data-toggle="modal" data-target=".modal-doc-pessoal">Carregar Regime Casamento</label>
                                                            <?php
                                                        }else {
                                                            $extencao_outro_Regime_casam = explode('.',$outro_Regime_casam->_nome);
                                                            $dados_outro_Regime_casam = URL . $outro_Regime_casam->_caminho . $outro_Regime_casam->_nome;
                                                            if($extencao_outro_Regime_casam[count($extencao_outro_Regime_casam)-1] == 'pdf'){
                                                                ?>
                                                                <a class="btn btn-default"
                                                                   href="<?php echo $dados_outro_Regime_casam; ?>" target="_blank">
                                                                    Ver Regime Casamento
                                                                </a>
                                                                <?php
                                                            }else {
                                                                ?>
                                                                <label class="btn btn-default btn-ver"
                                                                       dados="<?php echo $dados_outro_Regime_casam; ?>"
                                                                       data-toggle="modal"
                                                                       data-target=".modal-imagem">
                                                                    Ver Regime Casamento
                                                                </label>
                                                                <?php
                                                            }
                                                        }
                                                        ?>
                                                    </div>
                                                </td>
                                            </tr>
                                            <hr>
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <?php } else {
                                                echo '<h5 style="color: red;">Sem dados para mostrar, porque o cliente não é casado.</h5>';
                                            }?>
                                    </div>
                                    <!-- end table -->
                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer" style="border: none; background-color: #fff;">
                        <a href="javascript:window.history.go(-1)" title="Voltar" class="btn btn-sm btn-default">Voltar</a>
                        <div class="pull-right f-s-14">
                            <i class="fa fa-clock-o"></i> Tempo de existência:
                            <span class="text-primary"><?php echo substr($hlp->tempoEspera($data, date('Y-m-d')), 1) ?></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="panel panel-primary" data-sortable-id="index-9">
                    <div class="panel-heading">
                        <h4 class="panel-title">Documentos</h4>
                    </div>
                    <div class="panel-body p-0 image gallery-group-1">
                        <ul class="todolist">
                                <?php
                                    switch($rtnImovel->_id_estado){
                                        case 1: echo '<li><a href="#" class="todolist-container doc-fase" data-toggle="modal" data-target=".modal-doc-proc" tipo="pagamento">
                                                    <div class="todolist-input"><i class="fa text-primary"><input type="checkbox" id="checkBox"/></i></div>
                                                    <div class="todolist-title">Carregar Pagamento</div></a></li>';
                                            break;
                                        case 2:
                                            $pagamentoI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'pagamento');
                                            $extencao_pagamento = explode('.',$pagamentoI->_nome);
                                            $dados_pagamento = URL . $pagamentoI->_caminho . $pagamentoI->_nome;
                                            if($extencao_pagamento[count($extencao_pagamento)-1] == 'pdf'){
                                                echo '<li><a class="todolist-container" href="'.$dados_pagamento.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>        
                                                <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_pagamento . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }

                                            $sisaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'sisa');

                                            if ($sisaI == false  || !is_object($sisaI)) {
                                                echo '<li><a href="#" class="todolist-container doc-fase" data-toggle="modal" data-target=".modal-doc-proc" tipo="sisa">
                                                    <div class="todolist-input"><i class="fa text-primary"><input type="checkbox" id="checkBox"/></i></div>
                                                    <div class="todolist-title">Carregar Imposto SISA</div>
                                                    </a></li>';
                                            } else {
                                                $extencao_sisa = explode('.', $sisaI->_nome);
                                                $dados_sisa = URL . $sisaI->_caminho . $sisaI->_nome;
                                                if ($extencao_sisa[count($extencao_sisa) - 1] == 'pdf') {
                                                    echo '<li><a class="todolist-container btn-ver" href="'.$dados_sisa.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                                } else {
                                                    echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_sisa . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                                }
                                            }

                                            $certi_matricialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'certidao-matricial');

                                            if ($certi_matricialI == false  || !is_object($certi_matricialI)) {
                                                echo '<li><a href="#" class="todolist-container doc-fase" data-toggle="modal" data-target=".modal-doc-proc" tipo="certidao-matricial">
                                                    <div class="todolist-input"><i class="fa text-primary"><input type="checkbox" id="checkBox"/></i></div>
                                                    <div class="todolist-title">Carregar Certidão Matricial</div>
                                                    </a></li>';
                                            } else {
                                                $extencao_certi_matricial = explode('.', $certi_matricialI->_nome);
                                                $dados_certi_matricial = URL . $certi_matricialI->_caminho . $certi_matricialI->_nome;
                                                if ($extencao_certi_matricial[count($extencao_certi_matricial) - 1] == 'pdf') {
                                                    echo '<li><a class="todolist-container btn-ver" href="'.$dados_certi_matricial.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                                } else {
                                                    echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_certi_matricial . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                                }
                                            }
                                            break;
                                        case 3:
                                            $pagamentoI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'pagamento');

                                            $extencao_pagamento = explode('.',$pagamentoI->_nome);
                                            $dados_pagamento = URL . $pagamentoI->_caminho . $pagamentoI->_nome;
                                            if($extencao_pagamento[count($extencao_pagamento)-1] == 'pdf'){
                                                echo '<li><a class="todolist-container" href="'.$dados_pagamento.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>        
                                                <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_pagamento . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            $sisaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'sisa');

                                            $extencao_sisa = explode('.', $sisaI->_nome);
                                            $dados_sisa = URL . $sisaI->_caminho . $sisaI->_nome;
                                            if ($extencao_sisa[count($extencao_sisa) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_sisa.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_sisa . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            }
                                            $certi_matricialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'certidao-matricial');

                                            $extencao_certi_matricial = explode('.', $certi_matricialI->_nome);
                                            $dados_certi_matricial = URL . $certi_matricialI->_caminho . $certi_matricialI->_nome;
                                            if ($extencao_certi_matricial[count($extencao_certi_matricial) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_certi_matricial.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_certi_matricial . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            }

                                            $escritura_publicaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'escritura-publica');

                                            echo '<li><a href="#" class="todolist-container doc-fase" data-toggle="modal" data-target=".modal-doc-proc" tipo="escritura-publica">
                                                <div class="todolist-input"><i class="fa text-primary"><input type="checkbox" id="checkBox"/></i></div>
                                                <div class="todolist-title">Carregar Escritura Pública</div>
                                                </a></li>';
                                            break;
                                        case 4:
                                            $pagamentoI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'pagamento');

                                            $extencao_pagamento = explode('.',$pagamentoI->_nome);
                                            $dados_pagamento = URL . $pagamentoI->_caminho . $pagamentoI->_nome;
                                            if($extencao_pagamento[count($extencao_pagamento)-1] == 'pdf'){
                                                echo '<li><a class="todolist-container" href="'.$dados_pagamento.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>        
                                                <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_pagamento . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            $sisaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'sisa');

                                            $extencao_sisa = explode('.', $sisaI->_nome);
                                            $dados_sisa = URL . $sisaI->_caminho . $sisaI->_nome;
                                            if ($extencao_sisa[count($extencao_sisa) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_sisa.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_sisa . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            }
                                            $certi_matricialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'certidao-matricial');

                                            $extencao_certi_matricial = explode('.', $certi_matricialI->_nome);
                                            $dados_certi_matricial = URL . $certi_matricialI->_caminho . $certi_matricialI->_nome;
                                            if ($extencao_certi_matricial[count($extencao_certi_matricial) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_certi_matricial.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_certi_matricial . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            }
                                            $escritura_publicaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'escritura-publica');

                                            $extencao_escritura_publica = explode('.', $escritura_publicaI->_nome);
                                            $dados_escritura_publica = URL . $escritura_publicaI->_caminho . $escritura_publicaI->_nome;
                                            if ($extencao_escritura_publica[count($extencao_escritura_publica) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_escritura_publica.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Escritura Pública</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_escritura_publica . '" data-toggle="modal" data-target=".modal-imagem">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Escritura Pública</div></a></li>';
                                            }

                                            $registo_predialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'registo-predial');

                                            if ($registo_predialI == false  || !is_object($registo_predialI)) {
                                                echo '<li><a href="#" class="todolist-container doc-fase" data-toggle="modal" data-target=".modal-doc-proc" tipo="registo-predial">
                                                <div class="todolist-input"><i class="fa text-primary"><input type="checkbox" id="checkBox"/></i></div>
                                                <div class="todolist-title">Carregar Registo Predial</div>
                                                </a></li>';
                                            } else {
                                                $extencao_registo_predial = explode('.', $registo_predialI->_nome);
                                                $dados_registo_predial = URL . $registo_predialI->_caminho . $registo_predialI->_nome;
                                                if ($extencao_registo_predial[count($extencao_registo_predial) - 1] == 'pdf') {
                                                    echo '<li><a class="todolist-container btn-ver" href="'.$dados_registo_predial.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Registo Predial</div></a></li>';
                                                } else {
                                                    echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_registo_predial . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Registo Predial</div></a></li>';
                                                }
                                            }
                                            break;
                                        case 5:
                                            $pagamentoI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'pagamento');

                                            $extencao_pagamento = explode('.',$pagamentoI->_nome);
                                            $dados_pagamento = URL . $pagamentoI->_caminho . $pagamentoI->_nome;
                                            if($extencao_pagamento[count($extencao_pagamento)-1] == 'pdf'){
                                                echo '<li><a class="todolist-container" href="'.$dados_pagamento.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>        
                                                <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_pagamento . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Pagamento</div></a></li>';
                                            }
                                            $sisaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'sisa');

                                            $extencao_sisa = explode('.', $sisaI->_nome);
                                            $dados_sisa = URL . $sisaI->_caminho . $sisaI->_nome;
                                            if ($extencao_sisa[count($extencao_sisa) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_sisa.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_sisa . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Imposto SISA</div></a></li>';
                                            }
                                            $certi_matricialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'certidao-matricial');

                                            $extencao_certi_matricial = explode('.', $certi_matricialI->_nome);
                                            $dados_certi_matricial = URL . $certi_matricialI->_caminho . $certi_matricialI->_nome;
                                            if ($extencao_certi_matricial[count($extencao_certi_matricial) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_certi_matricial.'" target="_blank">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_certi_matricial . '" data-toggle="modal" data-target=".modal-imagem">
                                                    <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                    <div class="todolist-title">Ver Certidão Matricial</div></a></li>';
                                            }
                                            $escritura_publicaI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'escritura-publica');

                                            $extencao_escritura_publica = explode('.', $escritura_publicaI->_nome);
                                            $dados_escritura_publica = URL . $escritura_publicaI->_caminho . $escritura_publicaI->_nome;
                                            if ($extencao_escritura_publica[count($extencao_escritura_publica) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_escritura_publica.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Escritura Pública</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_escritura_publica . '" data-toggle="modal" data-target=".modal-imagem">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Escritura Pública</div></a></li>';
                                            }

                                            $registo_predialI = $doc_pessoalDao->listarPelaChaveEstrangeiraAND("doc_gerado","_id_imovel",$rtnImovel->_id,"_tipo",'registo-predial');

                                            $extencao_registo_predial = explode('.', $registo_predialI->_nome);
                                            $dados_registo_predial = URL . $registo_predialI->_caminho . $registo_predialI->_nome;
                                            if ($extencao_registo_predial[count($extencao_registo_predial) - 1] == 'pdf') {
                                                echo '<li><a class="todolist-container btn-ver" href="'.$dados_registo_predial.'" target="_blank">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Registo Predial</div></a></li>';
                                            } else {
                                                echo '<li><a href="#" class="todolist-container btn-ver" dados="' . $dados_registo_predial . '" data-toggle="modal" data-target=".modal-imagem">
                                                <div class="todolist-input"><i class="fa fa-check-square-o text-primary"></i></div>
                                                <div class="todolist-title">Ver Registo Predial</div></a></li>';
                                            }
                                            break;
                                    }
                                ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->


<div class="modal fade modal-imagem" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div class="profile-image" style="overflow: auto;">
                    <img id="img-modal-ver" src="" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
            </div>

        </div>
    </div>
</div>

<div class="modal fade modal-doc-proc" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title left"><span class="text-info">SIC</span>Doc informa</h4>
            </div>
            <form method="post" enctype="multipart/form-data" action="<?php echo URL?>processo/carregarFileDocProc">
                <div class="modal-body">
                    <div class="profile-section">
                            <div class="form-group">
                                <input type="file" name="carregar-doc-proc" id="carregar-doc-proc" multiple />
                                <input type="hidden" name="caminho-pasta-fase" id="caminho-pasta-fase" value="doc_gerado" />
                                <input type="hidden" name="id-imovel" id="id-imovel" value="<?php echo $rtnImovel->_id?>" />
                                <input type="hidden" name="tipo-doc-proc" id="tipo-doc-proc" value="" />
                                <input type="hidden" name="idCc" id="idCc" value="<?php echo $idCliente;?>" />
                                <input type="hidden" name="estado-imovel" id="estado-imovel" value="<?php echo $rtnImovel->_id_estado;?>" />
                            </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade modal-doc-pessoal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span class="text-info">SIC</span>Doc informa</h4>
            </div>
            <form method="post" enctype="multipart/form-data" action="<?php echo URL?>processo/carregarFileDocPessoal">
                <div class="modal-body">
                    <div class="profile-section">
                            <div class="form-group">
                                <input type="file" name="carregar-doc-pessoal" id="carregar-doc-pessoal" multiple />
                                <input type="hidden" name="caminho-pasta" id="caminho-pasta" value="doc_pessoal" />
                                <input type="hidden" name="tipo-doc" id="tipo-doc" value="" />
                                <input type="hidden" name="idC" id="idC" value="<?php echo $idCliente;?>" />
                            </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </form>
        </div>
    </div>
</div>
