
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Procurar Funcionário</h3>
            </div>

            <div class="title_right">
                <div class="col-md-7 col-sm-7 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control btn-buscar-processo" placeholder="Escreva aqui...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">&nbsp; Ir!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Resultado da busca</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content resultado-da-busca-processo">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>Nº do Processo</th>
                                <th>Estado</th>
                                <th>Data de Criação</th>
                                <th>Acção</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Mark</td>
                                <td>Otto</td>
                                <td>@mdo</td>
                                <td>Otto</td>
                                <td><a href="#">Saber mais <i class="fa fa-eye right"></i></a></td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                                <td>@fat</td>
                                <td>Thornton</td>
                                <td><a href="#">Saber mais <i class="fa fa-eye right"></i></a></td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Larry</td>
                                <td>the Bird</td>
                                <td>@twitter</td>
                                <td>the Bird</td>
                                <td><a href="#">Saber mais <i class="fa fa-eye right"></i></a></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->