<?php
$att = new Atributo();
$fun = new FuncionarioDao();
$funcionario = $fun->listarTodosPor("funcionario",'_nome');

?>
<!-- page content -->
<div class="right_col" role="main" style="margin-bottom: -10px;">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Lista de todos Funcionário</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Os Funcionário estão organizados por nome</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content resultado-da-busca-processo">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Primeiro nome</th>
                                    <th>Último nome</th>
                                    <th>Nº do B.I</th>
                                    <th>Área</th>
                                    <th>Telefone</th>
                                    <th>Acção</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php $count=1; foreach ($funcionario as $item):?>
                                <tr>
                                    <th scope="row"><?php echo $count;?></th>
                                    <td><?php echo $item->_nome?></td>
                                    <td><?php echo $item->_apelido?></td>
                                    <td><?php echo $item->_num_bi?></td>
                                    <td>
                                    <?php
                                        if($item->_id_area == '1')
                                            echo 'Back-Office';
                                        elseif ($item->_id_area == '2')
                                            echo 'Gerência';
                                    ?>
                                    </td>
                                    <td><?php echo $item->_telefone?></td>
                                    <td><a href="<?php echo URL.$att->getContoller().'/perfil_/'.base64_encode($item->_id);?>">Ver <i class="fa fa-eye right"></i></a></td>
                                </tr>
                            <?php $count+=1; endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->