
<!DOCTYPE html>
<html lang="pt-pt">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI Bootstrap 4 Admin Template">
    <meta name="author" content="Lukasz Holeczek">
    <meta name="keyword" content="CoreUI Bootstrap 4 Admin Template">
    <!-- <link rel="shortcut icon" href="assets/ico/favicon.png"> -->

    <title>SICDoc | Login</title>

    <!-- Icons -->
    <link href="<?php echo URL?>public/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php echo URL?>public/css/simple-line-icons.css" rel="stylesheet">

    <!-- Main styles for this application -->
    <link href="<?php echo URL?>public/css/style.css" rel="stylesheet">

    <link id="id_bootstrap" href="<?php echo URL?>1public/bootstrap/css/bootstrap.css" rel="stylesheet">

</head>

<body class="app flex-row align-items-center">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-group mb-0">
                <div class="card p-4">
                    <div class="card-body ">
                        <h1>Login</h1>
                        <p class="text-muted">Entre para aceder a tua conta</p>
                        <form action="<?php echo URL?>authentication/logon" method="POST" class="frm-login">
                            <div class="input-group mb-3">
                                <span class="input-group-addon"><i class="icon-user"></i></span>
                                <input type="text" class="form-control txt-clear" name="user" placeholder="Nome de utilizador" required>
                            </div>
                            <div class="input-group mb-4">
                                <span class="input-group-addon"><i class="icon-lock"></i></span>
                                <input type="password" class="form-control txt-clear" name="senha" placeholder="Senha" required>
                            </div>
                            <div class="text-center">
                                <label class="text-center erro-login text-danger">&nbsp;</label>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <button type="submit" class="btn btn-primary px-4 btn-login">Entrar</button>
                                </div>
                                <div class="col-6 text-right">
                                    <a href="<?php echo URL?>recuperarSenha" class="btn btn-link px-0 btn-esquecer-senha">Esqueceu a senha?</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
                    <div class="card-body text-center">
                        <h2>SICDoc</h2>
                        <p>Sistema de Informação e Controlo Documental</p>
                        <div class="row justify-content-center">
                            <img src="<?php echo URL?>public/img/logo2.png" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade calback-login-front-end" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title left"><span class="text-info">SIC</span>Doc informa</h6>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger fade in m-b-15 text-center">
                    <i class="fa fa-lock m-t-5" style="font-size: large"></i> A sua conta está desactivada.<br>Entre em contacto com o Administrador do Sistema.
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" id="id_fechar_modal" class="btn btn-sm btn-inverse" data-dismiss="modal">Fechar</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap and necessary plugins -->
<script src="<?php echo URL?>public/jquery/jquery-1.9.1.min.js"></script>
<script src="<?php echo URL?>public/node_modules/popper.js/dist/umd/popper.min.js"></script>
<script src="<?php echo URL?>public/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo URL?>public/gulp-tasks/build-dist.js"></script>
<script src="<?php echo URL?>public/js/login.js"></script>

</body>
</html>